project:
  type: website

website:
  site-url: https://iqb-vocabs.github.io/p15/
  favicon: favicon.ico
  page-navigation: true
  repo-url: https://github.com/iqb-vocabs/p15/
  navbar:
    logo: IQB-klein.png
    search: true
    left:
        - href: index.qmd
          text: "Metadatenprofile für Testaufgaben: Mathematik Primar 2004"
    right:
      - icon: github
        href: https://github.com/iqb-vocabs/p15
        aria-label: Source Code

lang: de

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
